[package]
name    = "wtr"
version = "0.0.1"
authors = ["Liam <liam@scalzulli.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.21"
snafu     = "0.6.10"

[dependencies.reqwest]
version  = "0.11"
features = ["blocking", "json"]
